# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
    name = "News"
    pageRef = "news"
    weight = 10

[[main]]
    name = "Research"
    pageRef = "research"
    weight = 20

[[main]]
    name = "Software Supply-Chain Security"
    parent = "Research"
    pageRef = "supply-chain"
    weight = 21

[[main]]
    name = "Acceleration and Scaleout of Software Systems"
    parent = "Research"
    pageRef = "acceleration"
    weight = 22


[[main]]
    name = "Towards Secure Scalable Computing"
    parent = "Research"
    pageRef = "ssc"
    weight = 23

[[main]]
    name = "Automating Correctness for Modern Software Systems"
    parent = "Research"
    pageRef = "correctness"
    weight = 24

[[main]]
    name = "Team"
    pageRef = "team"
    weight = 30

[[main]]
    name = "Publications"
    pageRef = "publications"
    weight = 40

[[main]]
    name = "Contact"
    pageRef = "contact"
    weight = 50

[[main]]
    name = "BrownSys"
    url = "https://systems.cs.brown.edu"
    weight = 60

[[main]]
    name = "Accessibility"
    url = "https://studentaccessibility.brown.edu"
    weight = 70
